name: Django CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 1: Save the PEM key from the secret with proper newlines
    - name: Save PEM key from secret
      run: |
        echo "${{ secrets.EC2_PEM_KEY }}" | sed 's/\\n/\n/g' > test-cicd-deployment-kp.pem  # Correct newline format
        chmod 600 test-cicd-deployment-kp.pem  # Ensure correct permissions

    # Step 2: Test SSH connection
    - name: Test SSH Connection
      run: |
        ssh -i test-cicd-deployment-kp.pem -o StrictHostKeyChecking=no -o BatchMode=yes ubuntu@ec2-52-54-98-30.compute-1.amazonaws.com "echo Connected to EC2" || echo "Connection Failed"

    # Step 3: Deploy to EC2 instance if tests pass and SSH connection works
    - name: Deploy to EC2 instance
      if: success()  # Only deploy if tests pass
      run: |
        ssh -i test-cicd-deployment-kp.pem -o StrictHostKeyChecking=no -o BatchMode=yes ubuntu@ec2-52-54-98-30.compute-1.amazonaws.com << 'EOF'
          cd ~/actions-runner/_work/Deployment/Deployment
          git pull origin main
          python manage.py migrate
          nohup python3 manage.py runserver 0.0.0.0:8000 &  # Run the Django server
          sudo systemctl restart nginx  # Restart NGINX
        EOF
