name: Django CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Tests
      run: |
        python manage.py test

    - name: Save PEM key from secret
      run: |
        echo "${{ secrets.EC2_PEM_KEY }}" | tr -d '\r' > test-cicd-deployment-kp.pem
        chmod 400 test-cicd-deployment-kp.pem

    - name: Deploy to NGINX Server
      if: success()  # Only deploy if tests pass
      run: |
        ssh -o StrictHostKeyChecking=no -i "test-cicd-deployment-kp.pem" ubuntu@ec2-52-54-98-30.compute-1.amazonaws.com << 'EOF'
          cd /actions-runner/_work/Deployment
          git pull origin main
          python manage.py migrate
          sudo systemctl restart nginx
        EOF
