name: Django CI

on:
  push:
    branches: [ "main" ]

concurrency:
  group: "django-ci-${{ github.ref }}"
  cancel-in-progress: true  # Cancel the previous run if it's still in progress

jobs:
  build:
    runs-on: self-hosted
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        # Update package list and install NGINX and pip
        sudo apt update
        sudo apt install -y nginx python3-pip
        
        # Install Gunicorn
        pip install gunicorn
        
        # Install Django project's dependencies
        pip install -r ~/actions-runner/_work/Deployment/Deployment/requirements.txt  # Adjust path as needed

    - name: Check Current Directory
      run: pwd

    - name: List Files
      run: ls -la ~/actions-runner/_work/Deployment/Deployment/

    - name: Create Static Directory
      run: |
        mkdir -p ~/actions-runner/_work/Deployment/Deployment/staticfiles  # Adjust path if needed

    - name: Collect Static Files
      run: |
        cd ~/actions-runner/_work/Deployment/Deployment
        python manage.py collectstatic --noinput

    - name: Migrate Database
      run: |
        cd ~/actions-runner/_work/Deployment/Deployment
        python manage.py migrate

    - name: Kill Existing Gunicorn Process
      run: |
        pkill gunicorn || true
        ps aux | grep gunicorn  # List any running Gunicorn processes

    - name: Start Gunicorn
      run: |
        # Start Gunicorn with UNIX socket
        gunicorn --bind unix:gunicorn.sock --chdir ~/actions-runner/_work/Deployment/Deployment Deployment.wsgi:application --timeout 10
