name: Django CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted  

    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        python manage.py test

    - name: Deploy to Server
      if: success()  # Only deploy if tests pass
      run: |
        ssh -o StrictHostKeyChecking=no -i "test-cicd-deployment-kp.pem" ubuntu@ec2-52-54-98-30.compute-1.amazonaws.com "cd /var/www/Deployment && git pull origin main && python manage.py migrate && sudo systemctl restart nginx"
